### PR TITLE
WIP Rewrite of readme after working through original

### PR DESCRIPTION
**Pull request by Treblesteph**

### CODE REVIEW

**Review by gedankenstuecke — COMMENTED** [review]
The changes look good to me! I noticed that the `README` still contains the `foreman` instructions. IIRC this app already works nicely with the `heroku` CLI client for the local deployment? And indeed, later down the `README` the `heroku` CLI is described for deploying the whole thing. 

I would suggest removing the references to `foreman` and instead focusing on the `heroku` CLI? That way we can save one dependency that people have to install/learn?

**Comment by Treblesteph** [comment]
link to our slack should be http://slackin.openhumans.org

**Review by gedankenstuecke — CHANGES_REQUESTED** [review]
We also want to switch our projects to use `pipenv` as the default manager of python dependencies. The `README` should reflect this and the repo should contain the `Pipfile` to allow to install easily via `pipenv install` 🙂

**Comment by mcescalante** [comment]
Okay, I just committed updates that removes `virtualenv` and adds `pipenv`, removes `foreman` for `heroku` and has some minor spelling edits (I tried all the pipenv and heroku commands that I replaced in here, they work!). Feel free to give it a peek and let me know if there are other edits.

**Review by gedankenstuecke — CHANGES_REQUESTED** [review]
Looks good to me now. The only thing missing is the correct link for joining as far as I can see! (http://slackin.openhumans.org would be the right one)

Once that's done 👍for merging from me!

**Review by gedankenstuecke — APPROVED** [review]
:shipit:

**Pull request merged**
