### PR TITLE
Improve README.md

### PR DESCRIPTION
**Pull request by manaswinidas**
Fixed minor typographical error in README.md

### CODE REVIEW

**Comment by gedankenstuecke** [comment]
Does this close #7? :)

**Comment by manaswinidas** [comment]
Yes it closes #7

**Comment by gedankenstuecke** [comment]
Great. For further pull requests: If you put `closes #7` or any other issue number into the title/description of your pull request the issue will automatically be closed once the pull request is merged. :-)

**Comment by manaswinidas** [comment]
Yes, That just slipped from my mind. I'll keep that in mind from now on. Thanks for merging!

**Comment by gedankenstuecke** [comment]
No worries, I wasn't sure whether you were aware of that feature already 🙂

**Pull request merged**
